name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SnowSQL
        run: |
          curl -O curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowflake-snowsql-1.2.27-1.x86_64.rpm
          sudo rpm -ivh snowflake-snowsql-1.2.27-1.x86_64.rpm

      - name: Set up Snowflake Config
        run: |
          mkdir ~/.snowsql
          echo "[connections]" >> ~/.snowsql/config
          echo "accountname = ${SNOWFLAKE_ACCOUNT}" >> ~/.snowsql/config
          echo "username = ${SNOWFLAKE_USER}" >> ~/.snowsql/config
          echo "password = ${SNOWFLAKE_PASSWORD}" >> ~/.snowsql/config

      - name: Deploy to Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SF_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          find ./dbscripts -name '*.sql' -print0 | sort -z | xargs -0 cat | ./snowflake-snowsql-1.2.27-1.x86_64/snowsql
