name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SF_SCHEMA }}
        run: |
          snowflake_command() {
            sql_command="$1"
            snowsql_command="snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD -d $SNOWFLAKE_DATABASE -s $SNOWFLAKE_SCHEMA -q \"\$sql_command\""
            eval $snowsql_command
          }

          find ./dbscripts -name '*.sql' -print0 | sort -z | while IFS= read -r -d '' file; do
            echo "Executing SQL file: $file"
            snowflake_command "$(cat "$file")"
          done
